apiVersion: v1
kind: Service
metadata:
  name: newsapp-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: newsapp-pub
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: newsapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: newsapp-notifications-pub
    spec:
      volumes:
      - name: notifications-pub-sa-key
        secret:
          secretName: service-account-creds
      containers:
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "--http_port=8081",
            "--backend=127.0.0.1:8080",
            "--service=newsapp.endpoints.gcp-newsapp-notifications-{{env}}.cloud.goog",
            "--rollout_strategy=managed"
          ]
        - name: notifications-pub-container
          image: us.gcr.io/gcp-newsapp-notifications-{{env}}/gke/newsapp-notifications-pub:{{tag}}
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 1.1Gi
          env:
          - name: LOGGING_FILE
            value: "newsapp-pub-container"
          - name: GIT_HASH
            value: "{{tag}}"
          - name: GOOGLE_PROJECT_ID
            valueFrom:
              configMapKeyRef:
                name: newsapp-notifications
                key: google-project-id
          - name: PUBSUB_PROJECT_ID
            valueFrom:
              configMapKeyRef:
                name: newsapp-notifications
                key: pubsub-project-id
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: newsapp-notifications
                key: spring-profiles-active
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/notifications-credentials.json
          volumeMounts:
          - name: notifications-pub-sa-key
            mountPath: /var/secrets/google
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: db-notifications-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "db-notifications-ip"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - hosts:
    - "newsapp-notifications.endpoints.gcp-newsapp-notifications-{{env}}.cloud.goog"
    secretName: newsapp-notifications-pub-tls
  rules:
  - host: "newsapp-notifications.endpoints.gcp-newsapp-notifications-{{env}}.cloud.goog"
    http:
      paths:
      - path: /*
        backend:
          serviceName: newsapp-notifications-service
          servicePort: 80
